name: SSH Login and Create Test File

on:
  push:
    branches:
      - main

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
      - name: Create SSH directory
        run: mkdir -p ~/.ssh
        
      - name: Check if known_hosts exists
        run: test -f ~/.ssh/known_hosts || touch ~/.ssh/known_hosts
        
      - name: Add host key to known hosts
        run: ssh-keyscan -H ${{ secrets.ftp_server }} >> ~/.ssh/known_hosts

      - name: Debug ssh-keyscan
        run: ssh-keyscan -H ${{ secrets.ftp_server }}

      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          key: ${{ secrets.ftp_private_key }}
          password: ${{ secrets.ftp_password }}
          script: |
            cd /var/
            sudo touch testdatei
            scp testdatei ${{ secrets.ftp_user }}@${{ secrets.ftp_server }}:/var

