name: SSH Login and Create Test File

on:
  push:
    branches:
      - main

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
      - name: Create SSH directory
        run: mkdir -p ~/.ssh
        
      - name: Check if known_hosts exists
        run: test -f ~/.ssh/known_hosts || touch ~/.ssh/known_hosts
        
      - name: Add host key to known hosts
        run: ssh-keyscan -H ${{ secrets.ftp_server }} >> ~/.ssh/known_hosts

      - name: Add public SSH key to authorized keys
        run: echo "${{ secrets.FTP_SSH_KEY_PUB }}" >> ~/.ssh/authorized_keys

      - name: SSH into server and create test file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          script: |
            cd /var/
            sudo touch testdatei
            scp testdatei ${{ secrets.ftp_user }}@${{ secrets.ftp_server }}:/var
